### ISSUE TITLE
PreloadTaskRunnable中是没写缓存吧？

### ISSUE THREAD

**Issue by xubigshu** [hzz9600/VideoCacheSample#2]
> 
    public void run() {
        PreloadLog.debug("PreloadTaskRunnable run():" + proxyUrl);

        HttpUrlSource newSourceNoCache = new HttpUrlSource(proxyUrl);

        try {
            newSourceNoCache.open(0);
            byte[] buffer = new byte[8 * 1024];//8K
            int bufferLen = buffer.length;
            int readBytes;
            int offset = 0;

            while ((offset + bufferLen <= preloadSize) && (readBytes = newSourceNoCache.read(buffer)) != -1) {
                //undo no need write.
                // out.write(buffer, 0, readBytes);
                offset += readBytes;
            }
        } catch (ProxyCacheException e) {
            e.printStackTrace();
        } finally {
            PreloadLog.debug("PreloadTaskRunnable is finished!!! ");
            try {
                newSourceNoCache.close();
            } catch (ProxyCacheException e) {
                e.printStackTrace();
            }
        }
    }

这个代码是没实现真的缓存吧？为啥给注释了呢

**Comment by hzz9600** [comment]
缓存实现是在代理服务器。预加载功能只要任意发起请求到代理服务器进行访问(你也可以自己用http访问代理服务器，不经过PreloadHelper)，发起方只要维持连接直到达到要缓存的大小后主动断开代理服务器，代理服务就停止缓存.
